### ISSUE TITLE
Beta test

### ISSUE THREAD

**Issue by larsen0815** [selvanair/openvpn-gui#5]
````
which take the name of the config (without the extension .ovpn) as a parameter
````

This is different to the behaviour before where the extension needed to be specified. I agree that it is better without, but then this should be unified without breaking old scripts (e.g. by automatically removing a trailing ".ovpn" if it exists (which in turn would break a connection where ".ovpn" actually is part of the name of that connection)).

````
openvpn-gui.exe --command connect mycompanyvpn
````
OK
Improvement: If there is no active gui process running, this should behave the same as "openvpn-gui.exe --connect mycompanyvpn.ovpn"

````
openvpn-gui.exe --command reconnect mycompanyvpn
````
OK

````
openvpn-gui.exe --command disconnect mycompanyvpn
````
Should show the status dialog (as it takes some time to complete and to be consistent)

````
openvpn-gui.exe --command status mycompanyvpn
````
OK

````
openvpn-gui.exe --command disconnect-all
````
**BUG**: nothing happens (and this too should show the status dialog)

````
If no action is specified, the running instance is notified to show a balloon to alert the user
````
Windows 10 slides in a balloon tip from the right side. When I right-click on that balloon tip, nothing happens. Perhaps, simply change the text to what it was before.

**Comment by selvanair** [comment]
Thanks for the feedback. All good suggestions and --disconnect-all is indeed buggy (will fix).

As for .ovpn, I think we can make it optional instead of not required.

> Improvement: If there is no active gui process running, this should behave the same as "openvpn-gui.exe --connect mycompanyvpn.ovpn"

Good -- will do.

Not showing status window during disconnect matches with the current behaviour when disconnect is chosen from the menu. Changing this needs some consideration. 

I haven't checked the balloon behaviour on Win10 -- will do. The right click is meant to be for the tray icon, so if the balloon doesn't appear attached to it, cuing the user with "GUI is already running.. " may be better, indeed.

**Comment by larsen0815** [comment]
> Not showing status window during disconnect matches with the current behaviour...
Then it's ok for me. Or it would need to be changed there too, but that would probably be another ticket.

**Comment by Deantwo** [comment]
> I haven't checked the balloon behaviour on Win10 -- will do. The right click is meant to be for the tray icon, so if the balloon doesn't appear attached to it, cuing the user with "GUI is already running.. " may be better, indeed.

Yeah, like I mentioned here: https://github.com/OpenVPN/openvpn-gui/issues/114#issuecomment-270633252

**Comment by selvanair** [comment]
Will change the text in the balloon to make sense when WIn10 style toast notifications are in use.
